name: 2. Ansible Playbook

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check ansible directory contents
        run: |
          cd ansible
          ls

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventario playbook.yaml