name: 4. Docker Image CI

on: 
  workflow_dispatch:
  push:
    branches: 
    - main
    - develop
    paths:
      - 'aplicativo/aplicativoNuevo/**'
      - 'kubernetes/**'
    
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: build and push
        run: |
          docker build -t plopez/app-plopez:1.0 aplicativo/aplicativoNuevo/.
          docker tag plopez/app-plopez:1.0  acrplopez.azurecr.io/app-plopez:1.0
          az acr login --name acrplopez
          docker push acrplopez.azurecr.io/app-plopez:1.0